apiVersion: apps/v1
kind: Deployment
metadata:
 name: mongodb-learn
 labels:
   app: mongodblearn
spec:
 selector:
   matchLabels:
     app: mongodblearn
 replicas: 1
 template:
   metadata:
     labels:
       app: mongodblearn
   spec:
     containers:
     - name: mongo
       image: mongo:6
       ports:
         - containerPort: 27017      
---
apiVersion: v1
kind: Service
metadata:
 name: mongodblearn-serivce
spec:
 selector:
   app: mongodblearn
 type: NodePort
 ports:
 - protocol: TCP
   port: 3000   
   targetPort: 27017
