apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
        - name: go-backend
          image: mysql-app
          imagePullPolicy: Never 
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: go-backend-config
