apiVersion: v1
kind: ConfigMap
metadata:
  name: go-backend-config
data:
  APP_NAME: test-service
  HTTP_PORT: "9000"
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  DB_HOST: mysql-service
  DB_USER: root
  DB_PASSWORD: root123
  DB_NAME: test_db
  DB_PORT: "3306"
  DB_DIALECT: mysql
