apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongodb-namespace
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend-namespace
data:
  DATABASE_URL: "mongodb://admin:admin123@mongodb-service.mongodb-namespace.svc.cluster.local:27017"

